"""ResearchCrew Utilities

Helper functions for workflow execution.
"""

from utils.handoffs import (
    create_handoff,
    log_handoff,
    safe_handoff,
    HandoffError,
    create_session_aware_handoff,
    extract_key_findings,
    extract_sources,
)
from utils.session_manager import (
    SessionManager,
    SessionState,
    ConversationTurn,
    get_session_manager,
    reset_session_manager,
)
from utils.knowledge_base import (
    KnowledgeBaseManager,
    KnowledgeEntry,
    SearchResult,
    get_knowledge_base,
    reset_knowledge_base,
)
from utils.context_manager import (
    ContextManager,
    TokenCounter,
    ContextCompressor,
    ContextWindow,
    ContextUsage,
    ContextWarning,
    CompressedContext,
    ModelConfig,
    MODEL_CONFIGS,
    get_context_manager,
    reset_context_manager,
)
from utils.tracing import (
    init_tracing,
    get_tracer,
    reset_tracing,
    trace_span,
    trace_tool,
    trace_agent,
    trace_llm_call,
    add_trace_context,
    get_trace_id,
    get_span_id,
)
from utils.metrics import (
    init_metrics,
    reset_metrics,
    get_metrics_text,
    record_request_duration,
    record_token_usage,
    record_error,
    update_error_rate,
    record_tool_call,
    update_tool_success_rate,
    record_knowledge_query,
    update_active_sessions,
    increment_active_sessions,
    decrement_active_sessions,
    metric_tool,
    metric_agent,
)
from utils.logging_config import (
    configure_logging,
    get_logger,
    LogContext,
)
from utils.debugging import (
    FailureInjector,
    FailureType,
    FailureEvent,
    DebugContext,
    diagnose_failure,
    get_debug_report,
    inject_failure_decorator,
    debug_span,
)
from utils.resilience import (
    TransientError,
    PermanentError,
    RateLimitError,
    NetworkError,
    ServerError,
    ClientError,
    AuthenticationError,
    ValidationError,
    classify_error,
    RetryConfig,
    RetryPolicy,
    RetryStats,
    retry_with_backoff,
    with_timeout,
    is_retriable,
    get_retry_wait,
    get_retry_stats,
    clear_retry_stats,
)
from utils.circuit_breaker import (
    CircuitBreaker,
    CircuitState,
    CircuitOpenError,
    CircuitBreakerConfig,
    CircuitBreakerPreset,
    CircuitBreakerStats,
    get_circuit_breaker,
    reset_circuit_breaker,
    reset_all_circuit_breakers,
    clear_circuit_breakers,
    get_all_circuit_stats,
    circuit_breaker_call,
    get_circuit_breaker_status,
    is_service_healthy,
)
from utils.fallback import (
    FallbackChain,
    FallbackStrategy,
    FallbackResult,
    FallbackStats,
    FallbackReason,
    FallbackExhaustedError,
    CachedFallbackStrategy,
    EmptyFallbackStrategy,
    LambdaFallbackStrategy,
    ModelFallbackChain,
    ModelConfig as FallbackModelConfig,
    DEFAULT_MODEL_CHAIN,
    create_search_fallback,
    create_url_reader_fallback,
    create_knowledge_search_fallback,
    register_fallback_chain,
    get_fallback_chain,
    get_model_fallback,
    set_model_fallback,
    get_all_fallback_stats,
    reset_fallback_stats,
    clear_fallback_registry,
    with_fallback,
)

__all__ = [
    # Handoff utilities
    "create_handoff",
    "log_handoff",
    "safe_handoff",
    "HandoffError",
    "create_session_aware_handoff",
    "extract_key_findings",
    "extract_sources",
    # Session management
    "SessionManager",
    "SessionState",
    "ConversationTurn",
    "get_session_manager",
    "reset_session_manager",
    # Knowledge base
    "KnowledgeBaseManager",
    "KnowledgeEntry",
    "SearchResult",
    "get_knowledge_base",
    "reset_knowledge_base",
    # Context management
    "ContextManager",
    "TokenCounter",
    "ContextCompressor",
    "ContextWindow",
    "ContextUsage",
    "ContextWarning",
    "CompressedContext",
    "ModelConfig",
    "MODEL_CONFIGS",
    "get_context_manager",
    "reset_context_manager",
    # Tracing
    "init_tracing",
    "get_tracer",
    "reset_tracing",
    "trace_span",
    "trace_tool",
    "trace_agent",
    "trace_llm_call",
    "add_trace_context",
    "get_trace_id",
    "get_span_id",
    # Metrics
    "init_metrics",
    "reset_metrics",
    "get_metrics_text",
    "record_request_duration",
    "record_token_usage",
    "record_error",
    "update_error_rate",
    "record_tool_call",
    "update_tool_success_rate",
    "record_knowledge_query",
    "update_active_sessions",
    "increment_active_sessions",
    "decrement_active_sessions",
    "metric_tool",
    "metric_agent",
    # Logging
    "configure_logging",
    "get_logger",
    "LogContext",
    # Debugging
    "FailureInjector",
    "FailureType",
    "FailureEvent",
    "DebugContext",
    "diagnose_failure",
    "get_debug_report",
    "inject_failure_decorator",
    "debug_span",
    # Resilience
    "TransientError",
    "PermanentError",
    "RateLimitError",
    "NetworkError",
    "ServerError",
    "ClientError",
    "AuthenticationError",
    "ValidationError",
    "classify_error",
    "RetryConfig",
    "RetryPolicy",
    "RetryStats",
    "retry_with_backoff",
    "with_timeout",
    "is_retriable",
    "get_retry_wait",
    "get_retry_stats",
    "clear_retry_stats",
    # Circuit Breaker
    "CircuitBreaker",
    "CircuitState",
    "CircuitOpenError",
    "CircuitBreakerConfig",
    "CircuitBreakerPreset",
    "CircuitBreakerStats",
    "get_circuit_breaker",
    "reset_circuit_breaker",
    "reset_all_circuit_breakers",
    "clear_circuit_breakers",
    "get_all_circuit_stats",
    "circuit_breaker_call",
    "get_circuit_breaker_status",
    "is_service_healthy",
    # Fallback Strategies
    "FallbackChain",
    "FallbackStrategy",
    "FallbackResult",
    "FallbackStats",
    "FallbackReason",
    "FallbackExhaustedError",
    "CachedFallbackStrategy",
    "EmptyFallbackStrategy",
    "LambdaFallbackStrategy",
    "ModelFallbackChain",
    "FallbackModelConfig",
    "DEFAULT_MODEL_CHAIN",
    "create_search_fallback",
    "create_url_reader_fallback",
    "create_knowledge_search_fallback",
    "register_fallback_chain",
    "get_fallback_chain",
    "get_model_fallback",
    "set_model_fallback",
    "get_all_fallback_stats",
    "reset_fallback_stats",
    "clear_fallback_registry",
    "with_fallback",
]
